/* Generated By:JavaCC: Do not edit this line. ExpRegsConstants.java */
package uniandes.teolen.parserJavaCC.parserTaller;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpRegsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 4;
  /** RegularExpression Id. */
  int EQUAL = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int COLON = 7;
  /** RegularExpression Id. */
  int RPAR = 8;
  /** RegularExpression Id. */
  int LPAR = 9;
  /** RegularExpression Id. */
  int LCOR = 10;
  /** RegularExpression Id. */
  int RCOR = 11;
  /** RegularExpression Id. */
  int MULT = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int REST = 14;
  /** RegularExpression Id. */
  int DIV = 15;
  /** RegularExpression Id. */
  int MOD = 16;
  /** RegularExpression Id. */
  int G = 17;
  /** RegularExpression Id. */
  int L = 18;
  /** RegularExpression Id. */
  int GE = 19;
  /** RegularExpression Id. */
  int LE = 20;
  /** RegularExpression Id. */
  int E = 21;
  /** RegularExpression Id. */
  int NE = 22;
  /** RegularExpression Id. */
  int DIGI = 23;
  /** RegularExpression Id. */
  int MAY = 24;
  /** RegularExpression Id. */
  int MIN = 25;
  /** RegularExpression Id. */
  int VAR = 26;
  /** RegularExpression Id. */
  int DEFINE = 27;
  /** RegularExpression Id. */
  int PRINT = 28;
  /** RegularExpression Id. */
  int IF = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\" \"",
    "\"=\"",
    "\",\"",
    "\":\"",
    "\")\"",
    "\"(\"",
    "\" [ \"",
    "\" ]\"",
    "\"*\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "<DIGI>",
    "<MAY>",
    "<MIN>",
    "\"var\"",
    "\"define\"",
    "\"print\"",
    "\"if\"",
  };

}
