/* Generated By:JavaCC: Do not edit this line. ExpRegConstants.java */
package expReg;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpRegConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Begin = 4;
  /** RegularExpression Id. */
  int CAMBIO = 5;
  /** RegularExpression Id. */
  int End = 6;
  /** RegularExpression Id. */
  int ALPHABET = 7;
  /** RegularExpression Id. */
  int ER_NAMEi = 8;
  /** RegularExpression Id. */
  int SYMB = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int MAY = 11;
  /** RegularExpression Id. */
  int MIN = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"BeginERS\"",
    "\"\\n\"",
    "\"EndERS\"",
    "\"Alphabet\"",
    "<ER_NAMEi>",
    "<SYMB>",
    "<DIGIT>",
    "<MAY>",
    "<MIN>",
    "\": {\"",
    "\",\"",
    "\"}\"",
    "\"=\"",
    "\"@\"",
    "\"$\"",
    "\"*\"",
    "\"+\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
  };

}
